### PR TITLE
Finish Chapter 4

### PR DESCRIPTION
**Pull request by phandinhlam**

### CODE REVIEW

**Comment by lamphan95** [comment]
rubocop_chapter4
ready

**Comment by phandinhlam** [comment]
rubocop_chapter4

**Comment by phandinhlam** [comment]
ready

**Comment by hhhhuy112** [comment]
commented
2 commit gộp lại em nhé

**Comment by phandinhlam** [comment]
ready

**Review by dothidiemthao — APPROVED** [review]

**Comment by dothidiemthao** [comment]
merged

**Pull request merged**
